name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/*.py'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**/*.py'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push the Docker image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 -t madrhr/pjportalbot --push .
